name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies and Build
        run: |
          yarn install
          yarn build
      - name: Cache build artifacts
        uses: actions/cache@v3
        id: cache-build
        with:
          path: |
            ./packages/*/dist
            ./node_modules/.yarn-state.yml
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Dry Run Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Confirm Dry Run
        run: echo "Dry run completed successfully. Ready for actual publishing."
      - name: Publish to npm
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
